# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ecc9f6e068758cb34c487445c661a58e955a8ffeabbf42c297e20dfd5796208e819434aebab323be1955cbf558b5c5e22de43a7b1bb95e5a231e8e62a258c86
  email: <%= ENV["EMAIL"] %>
  password: <%= ENV["PASSWORD"] %>

test:
  secret_key_base: ab6f83d09444898dc8ab4ee4812bed3ddbf1be5135a1204a02fb5ad048215cd57a315f6b02c9b27519424ccf3403b0249f201a39eea1455a89a0902b204caf20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
